enum Province {
  federal,
  punjab,
  sindh,
  khyberPakhtunkhwa,
  balochistan,
}

extension ProvinceX on Province {
  /// For UI
  String get toDisplayName {
    switch (this) {
      case Province.federal:
        return 'Federal Territory';
      case Province.punjab:
        return 'Punjab';
      case Province.sindh:
        return 'Sindh';
      case Province.khyberPakhtunkhwa:
        return 'Khyber Pakhtunkhwa';
      case Province.balochistan:
        return 'Balochistan';
    }
  }

  /// For APIs/URLs (kebab-case)
  String get toApiName => toDisplayName.toLowerCase().replaceAll(' ', '-');
}

enum City {
  // Federal
  islamabad,

  // Punjab
  ahmedNagerChatha,
  ahmadpurEast,
  aliKhanAbad,
  alipur,
  arifwala,
  attock,
  bhera,
  bhalwal,
  bahawalnagar,
  bahawalpur,
  bhakkar,
  burewala,
  chillianwala,
  chakwal,
  chichawatni,
  chiniot,
  chishtian,
  daska,
  daryaKhan,
  deraGhaziKhan,
  dhaular,
  dina,
  dinga,
  dipalpur,
  faisalabad,
  ferozewala,
  fatehJang,
  ghakharMandi,
  gojra,
  gujranwala,
  gujrat,
  gujarKhan,
  hafizabad,
  haroonabad,
  hasilpur,
  haveliLakha,
  jatoi,
  jalalpur,
  jattan,
  jampur,
  jaranwala,
  jhang,
  jhelum,
  kalabagh,
  karorLalEsan,
  kasur,
  kamalia,
  kamoke,
  khanewal,
  khanpur,
  kharian,
  khushab,
  kotAddu,
  jauharabad,
  lahore,
  lalamusa,
  layyah,
  liaquatPur,
  lodhran,
  malakwal,
  mamoori,
  mailsi,
  mandiBahauddin,
  mianChannu,
  mianwali,
  multan,
  murree,
  muridke,
  mianwaliBangla,
  muzaffargarh,
  narowal,
  nankanaSahib,
  okara,
  renalaKhurd,
  pakpattan,
  pattoki,
  pirMahal,
  qaimpur,
  qilaDidarSingh,
  rabwah,
  raiwind,
  rajanpur,
  rahimYarKhan,
  rawalpindi,
  sadiqabad,
  safdarabad,
  sahiwal,
  sanglaHill,
  saraiAlamgir,
  sargodha,
  shakargarh,
  sheikhupura,
  sialkot,
  sohawa,
  soianwala,
  siranwali,
  talagang,
  taxila,
  tobaTekSingh,
  vehari,
  wahCantonment,
  wazirabad,

  // Sindh
  badin,
  bhirkan,
  rajoKhanani,
  chak,
  dadu,
  digri,
  diplo,
  dokri,
  ghotki,
  haala,
  hyderabad,
  islamkot,
  jacobabad,
  jamshoro,
  jungshahi,
  kandhkot,
  kandiaro,
  karachi,
  kashmore,
  ketiBandar,
  khairpur,
  kotri,
  larkana,
  matiari,
  mehar,
  mirpurKhas,
  mithani,
  mithi,
  mehrabpur,
  moro,
  nagarparkar,
  naudero,
  naushahroFeroze,
  naushara,
  nawabshah,
  nazimabad,
  qambar,
  qasimabad,
  ranipur,
  ratodero,
  rohri,
  sakrand,
  sanghar,
  shahbandar,
  shahdadkot,
  shahdadpur,
  shahpurChakar,
  shikarpaur,
  sukkur,
  tangwani,
  tandoAdamKhan,
  tandoAllahyar,
  tandoMuhammadKhan,
  thatta,
  umerkot,
  warah,

  // Khyber Pakhtunkhwa
  abbottabad,
  adezai,
  alpuri,
  akoraKhattak,
  ayubia,
  bandaDaudShah,
  bannu,
  batkhela,
  battagram,
  birote,
  chakdara,
  charsadda,
  chitral,
  daggar,
  dargai,
  deraIsmailKhan,
  doaba,
  dir,
  drosh,
  hangu,
  haripur,
  karak,
  kohat,
  kulachi,
  lakkiMarwat,
  latamber,
  madyan,
  mansehra,
  mardan,
  mastuj,
  mingora,
  nowshera,
  paharpur,
  pabbi,
  peshawar,
  saiduSharif,
  shorkot,
  shewaAdda,
  swabi,
  swat,
  tangi,
  tank,
  thall,
  timergara,
  tordher,

  // Balochistan
  awaran,
  barkhan,
  chagai,
  deraBugti,
  gwadar,
  harnai,
  jafarabad,
  jhalMagsi,
  kacchi,
  kalat,
  kech,
  kharan,
  khuzdar,
  killaAbdullah,
  killaSaifullah,
  kohlu,
  lasbela,
  lehri,
  loralai,
  mastung,
  musakhel,
  nasirabad,
  nushki,
  panjgur,
  pishinValley,
  quetta,
  sherani,
  sibi,
  sohbatpur,
  washuk,
  zhob,
  ziarat,
}

extension CityX on City {
  /// Province for this city
  Province get province => _cityToProvince[this]!;

  /// For UI (proper spacing & capitalization; keeps known tokens)
  String get toDisplayName {
    // Custom fixes for multi-word tokens & proper casing
    final special = <City, String>{
      City.deraGhaziKhan: 'Dera Ghazi Khan',
      City.deraIsmailKhan: 'Dera Ismail Khan',
      City.karorLalEsan: 'Karor Lal Esan',
      City.mandiBahauddin: 'Mandi Bahauddin',
      City.qilaDidarSingh: 'Qila Didar Singh',
      City.saiduSharif: 'Saidu Sharif',
      City.shahpurChakar: 'Shahpur Chakar',
      City.tandoAdamKhan: 'Tando Adam Khan',
      City.tandoAllahyar: 'Tando Allahyar',
      City.tandoMuhammadKhan: 'Tando Muhammad Khan',
      City.naushahroFeroze: 'Naushahro Feroze',
      City.rahimYarKhan: 'Rahim Yar Khan',
      City.wahCantonment: 'Wah Cantonment',
      City.ketiBandar: 'Keti Bandar',
      City.jhalMagsi: 'Jhal Magsi',
      City.bandaDaudShah: 'Banda Daud Shah',
      City.pishinValley: 'Pishin Valley',
      City.naushara: 'Naushara',
      City.mianChannu: 'Mian Channu',
      City.mianwaliBangla: 'Mianwali Bangla',
      City.saraiAlamgir: 'Sarai Alamgir',
    };

    if (special.containsKey(this)) return special[this]!;

    final raw = name; // camelCase
    // Insert spaces before capital letters, then title case words
    final withSpaces = raw.replaceAllMapped(
      RegExp(r'(?<=[a-z])([A-Z])'),
      (m) => ' ${m.group(1)}',
    );
    return withSpaces
        .split(' ')
        .map((w) => w.isEmpty ? w : (w[0].toUpperCase() + w.substring(1)))
        .join(' ');
  }

  /// For APIs/URLs (kebab-case), based on display name
  String get toApiName =>
      toDisplayName.toLowerCase().replaceAll(RegExp(r'\s+'), '-');
}

/// Province → Cities (from your list)
final Map<Province, List<City>> provinceToCities = {
  Province.federal: const [
    City.islamabad,
  ],
  Province.punjab: const [
    City.ahmedNagerChatha,
    City.ahmadpurEast,
    City.aliKhanAbad,
    City.alipur,
    City.arifwala,
    City.attock,
    City.bhera,
    City.bhalwal,
    City.bahawalnagar,
    City.bahawalpur,
    City.bhakkar,
    City.burewala,
    City.chillianwala,
    City.chakwal,
    City.chichawatni,
    City.chiniot,
    City.chishtian,
    City.daska,
    City.daryaKhan,
    City.deraGhaziKhan,
    City.dhaular,
    City.dina,
    City.dinga,
    City.dipalpur,
    City.faisalabad,
    City.ferozewala,
    City.fatehJang,
    City.ghakharMandi,
    City.gojra,
    City.gujranwala,
    City.gujrat,
    City.gujarKhan,
    City.hafizabad,
    City.haroonabad,
    City.hasilpur,
    City.haveliLakha,
    City.jatoi,
    City.jalalpur,
    City.jattan,
    City.jampur,
    City.jaranwala,
    City.jhang,
    City.jhelum,
    City.kalabagh,
    City.karorLalEsan,
    City.kasur,
    City.kamalia,
    City.kamoke,
    City.khanewal,
    City.khanpur,
    City.kharian,
    City.khushab,
    City.kotAddu,
    City.jauharabad,
    City.lahore,
    City.lalamusa,
    City.layyah,
    City.liaquatPur,
    City.lodhran,
    City.malakwal,
    City.mamoori,
    City.mailsi,
    City.mandiBahauddin,
    City.mianChannu,
    City.mianwali,
    City.multan,
    City.murree,
    City.muridke,
    City.mianwaliBangla,
    City.muzaffargarh,
    City.narowal,
    City.nankanaSahib,
    City.okara,
    City.renalaKhurd,
    City.pakpattan,
    City.pattoki,
    City.pirMahal,
    City.qaimpur,
    City.qilaDidarSingh,
    City.rabwah,
    City.raiwind,
    City.rajanpur,
    City.rahimYarKhan,
    City.rawalpindi,
    City.sadiqabad,
    City.safdarabad,
    City.sahiwal,
    City.sanglaHill,
    City.saraiAlamgir,
    City.sargodha,
    City.shakargarh,
    City.sheikhupura,
    City.sialkot,
    City.sohawa,
    City.soianwala,
    City.siranwali,
    City.talagang,
    City.taxila,
    City.tobaTekSingh,
    City.vehari,
    City.wahCantonment,
    City.wazirabad,
  ],
  Province.sindh: const [
    City.badin,
    City.bhirkan,
    City.rajoKhanani,
    City.chak,
    City.dadu,
    City.digri,
    City.diplo,
    City.dokri,
    City.ghotki,
    City.haala,
    City.hyderabad,
    City.islamkot,
    City.jacobabad,
    City.jamshoro,
    City.jungshahi,
    City.kandhkot,
    City.kandiaro,
    City.karachi,
    City.kashmore,
    City.ketiBandar,
    City.khairpur,
    City.kotri,
    City.larkana,
    City.matiari,
    City.mehar,
    City.mirpurKhas,
    City.mithani,
    City.mithi,
    City.mehrabpur,
    City.moro,
    City.nagarparkar,
    City.naudero,
    City.naushahroFeroze,
    City.naushara,
    City.nawabshah,
    City.nazimabad,
    City.qambar,
    City.qasimabad,
    City.ranipur,
    City.ratodero,
    City.rohri,
    City.sakrand,
    City.sanghar,
    City.shahbandar,
    City.shahdadkot,
    City.shahdadpur,
    City.shahpurChakar,
    City.shikarpaur,
    City.sukkur,
    City.tangwani,
    City.tandoAdamKhan,
    City.tandoAllahyar,
    City.tandoMuhammadKhan,
    City.thatta,
    City.umerkot,
    City.warah,
  ],
  Province.khyberPakhtunkhwa: const [
    City.abbottabad,
    City.adezai,
    City.alpuri,
    City.akoraKhattak,
    City.ayubia,
    City.bandaDaudShah,
    City.bannu,
    City.batkhela,
    City.battagram,
    City.birote,
    City.chakdara,
    City.charsadda,
    City.chitral,
    City.daggar,
    City.dargai,
    City.deraIsmailKhan,
    City.doaba,
    City.dir,
    City.drosh,
    City.hangu,
    City.haripur,
    City.karak,
    City.kohat,
    City.kulachi,
    City.lakkiMarwat,
    City.latamber,
    City.madyan,
    City.mansehra,
    City.mardan,
    City.mastuj,
    City.mingora,
    City.nowshera,
    City.paharpur,
    City.pabbi,
    City.peshawar,
    City.saiduSharif,
    City.shorkot,
    City.shewaAdda,
    City.swabi,
    City.swat,
    City.tangi,
    City.tank,
    City.thall,
    City.timergara,
    City.tordher,
  ],
  Province.balochistan: const [
    City.awaran,
    City.barkhan,
    City.chagai,
    City.deraBugti,
    City.gwadar,
    City.harnai,
    City.jafarabad,
    City.jhalMagsi,
    City.kacchi,
    City.kalat,
    City.kech,
    City.kharan,
    City.khuzdar,
    City.killaAbdullah,
    City.killaSaifullah,
    City.kohlu,
    City.lasbela,
    City.lehri,
    City.loralai,
    City.mastung,
    City.musakhel,
    City.nasirabad,
    City.nushki,
    City.panjgur,
    City.pishinValley,
    City.quetta,
    City.sherani,
    City.sibi,
    City.sohbatpur,
    City.washuk,
    City.zhob,
    City.ziarat,
  ],
};

/// City → Province (built once; useful for quick reverse lookup)
final Map<City, Province> _cityToProvince = () {
  final map = <City, Province>{};
  provinceToCities.forEach((prov, cities) {
    for (final c in cities) {
      map[c] = prov;
    }
  });
  return Map<City, Province>.unmodifiable(map);
}();
